server:
  port: 8081

spring:
  application:
    name: Java-typing-game
  datasource:
    url: jdbc:mysql://localhost:3306/typing_game
    username: root
    password: Jay40984692$
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
